spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nba?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      max-lifetime: 10000

server:
  port: 8083

#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

elasticsearch:
  host: 192.168.1.103
  port: 9200




